version: '3'
services:
  server:
    working_dir: /server
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=rubberduckers
      - PGHOST=db
      - PGPASSWORD=rubberduck
      - PGDATABASE=habit-tracker
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /server
    command: bash -c "npm install && npm start"
  db:
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=habit-tracker
      - POSTGRES_USER=rubberduckers
      - POSTGRES_PASSWORD=rubberduck
volumes:
  dbdata:
