services:
  server:
    container_name: project_test_api
    environment: 
      - PGUSER=rubberduckers
      - PGHOST=db
      - PGPASSWORD=rubberduck
      - PGDATABASE=habit-tracker
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: project_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=habit-tracker
      - POSTGRES_USER=rubberduckers
      - POSTGRES_PASSWORD=rubberduck
volumes:
  test_db:
networks: 
  default:
    name: project_test
