version: '3'
services:
  server:
    image: node:14
    working_dir: /code
    volumes:
      - type: bind
        source: ./server
        target: /code
  db:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=rubberduckers
    volumes:
      - "./db:/docker-entrypoint-initdb.d/:ro"
